env:
  global:
    - CC_TEST_REPORTER_ID=38e521fe65e6e6bed425c2706043a5978be4a5de3bb5117a118fa5f6ee2df336

language: php

php:
  - 8.0

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

install:
  - composer install

script:
  - composer all

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
